### ISSUE TITLE
6. Сделать аудиоплеер

### ISSUE THREAD

**Issue by AlinaShmain** [AlinaShmain/musical-service#12]
- [x] создать HTML разметку аудиоплеера
- [x] стилизовать его
- [x] добавить отправку GET запроса аудиоданных в обработчике события click при нажатии на трек
- [x] декодировать бинарные данные, полученные с сервера, для воспроизведения через Web Audio API
- [x] реализовать воспроизведение трека
- [x] сделать перемещение точки воспроизведения по временной шкале
- [x] добавить остановку прослушивания по нажатию кнопки Pause
- [x] добавить остановку прослушивания по нажатию на строку с проигрывающимся треком
- [x] реализовать восстановление воспроизведения с точки остановки по нажатию на кнопку Resume
- [x] реализовать восстановление воспроизведения с точки остановки по нажатию на строку с проигрывающимся треком
- [x] воспроизводить следующий трек автоматически после окончания проигрывания текущего
- [x] обработать пропуск композиции по нажатию кнопки
- [x] перед проигрыванием трека сбрасывать текущий AudioState на случай если пользователь не дослушав текущую композицию нажмет прослушать следующую
- [x] блокировать кнопку Previous если проигрывается первый трек из списка, блокировать кнопку Next если - последний
- [x] если не было проиграно ни одного трека и была нажата кнопка Play, воспроизводить первый трек из списка на странице
- [x] добавить возможность возврата к предыдущему треку
- [x] добавить регулирование громкости
- [x] добавить оставшиеся аудиофайлы в локальное хранилище, добавить в бд схему трека пути до этих файлов, чтобы считывать их при запросе на проигрывание 
- [x] уменьшить область нажатия на строку с треком, чтобы можно было нажимать на Меню и Избранное без инициирования воспроизведения

**Comment by cyclist-nn** [comment]
Как успехи? что то давно ничего не меняется

**Comment by AlinaShmain** [comment]
Дошла до воспроизведения, долго возилась как передать arraybuffer для дэкодирования на клиенте, я коммичу, просто не пушу пока всю таску не доделаю

**Comment by cyclist-nn** [comment]
нам бы до 10 июля защиту провести

**Comment by AlinaShmain** [comment]
Тогда до конца июня у меня еще есть время доделать?

**Comment by cyclist-nn** [comment]
я как раз и мотивирую собраться

**Comment by AlinaShmain** [comment]
Я создала эту ветку и внесла туда изменения до того как понадобилось что-то исправлять в предыдущей ветке, я потом добавила этот коммит с помощью cherry-pick, но порядок то все равно другой, поэтому там конфликт возник, который не знаю как исправить

**Comment by cyclist-nn** [comment]
Надо было сделать ребейз новой ветки относительно мастера, или смержить мастер в новую. А так я что то на словах не догоняю что там вышло... Сделай хоть скрин может в git gui где дерево веток рисуется. 
--
Отправлено из Mail.ru для Android пятница, 18 июня 2021г., 23:01 +03:00 от AlinaShmain  ***@***.*** :

**Comment by AlinaShmain** [comment]
<img width="343" alt="Снимок экрана 2021-06-18 232739" src="https://user-images.githubusercontent.com/32477394/122613978-701fd580-d08e-11eb-9ad8-437a77142b77.png">
Может зарезолвить конфликты, которые в пул реквесте?

**Comment by AlinaShmain** [comment]
Я попыталась разрезолвить конфликты, но чтобы эти изменения сохранить мне надо сделать commit merge, я без вас не могу этого сделать. Другой вариант если мне сделать rebase master, то нужно убрать коммит, который я cherry-pick-ом добавила, а я что то не решаюсь использовать reset

**Comment by cyclist-nn** [comment]
давай созвон, посмотрим

**Comment by AlinaShmain** [comment]
Хорошо, можно где то в 12? Не знаю точного времени, как с больницы вернусь

**Comment by cyclist-nn** [comment]
да в 12 можно, надеюсь ничего серьезного со здоровьем

**Comment by AlinaShmain** [comment]
Да ничего, я наверное в 12 я не успею, тут очередь, можно я тогда напишу
как приду в скайп, у меня будет ещё вопрос по проекту
