### ISSUE TITLE
4. Переделать модальное окно с использованием material 

### ISSUE THREAD

**Issue by AlinaShmain** [AlinaShmain/musical-service#8]
Изменила маршрутизацию модального окна (ms-app-routing.module.ts):
```
{ path: "home", component: HomeComponent, },
{ path: "signIn", component: SignInComponent, canActivate: [AuthModalGuard] },
{ path: "signUp", component: SignUpComponent, canActivate: [AuthModalGuard] },
```

Открытие модального окна теперь происходит в обработчике события click кнопки Login (home.component.html):
`<button mat-raised-button color="accent" (click)="onOpen()">Login</button>`
(home.component.ts):
 ```
onOpen(): void {
    this.usersService.isOpenAuthModal = true;
    const dialogRef = this.dialog.open(AuthModalComponent, {});
    dialogRef.afterClosed().pipe(takeUntil(this.destroy$)).subscribe((result) => {
      this.router.navigateByUrl("/");
    });
  }
```

Навигация по формам регистрации/аутентификации (auth-modal.component.html):
```
<nav mat-tab-nav-bar mat-align-tabs="center">
    <a mat-tab-link routerLink="signIn" routerLinkActive="active">Sign In</a>
    <a mat-tab-link routerLink="signUp" routerLinkActive="active">Sign Up</a>
</nav>
<router-outlet></router-outlet>
```
(auth-modal.component.ts):
```
 ngOnInit(): void {
    this.router.navigate(["./signIn"], { relativeTo: this.route });
 }
```

Теперь проблема, если мы в адресной строке браузера обратимся по url /signIn или /signUp, то модальное окно не создастся, потому что оно открывается в обработчике кнопки Login, и тогда код формы вставится прямо вместо кода home.component.html. Я предлагаю решить эту проблему повесив guard на маршруты /signIn и /signUp, который запретит доступ к ним если диалоговое окно не создано с помощью булевой переменной isOpenAuthModal. Значение этой переменной устанавливается в true при открытии диалогового окна и в false при закрытии.(auth-modal-guard.ts):
```
export class AuthModalGuard implements CanActivate {
    private isOpenAuthModal: boolean = false;

    constructor(private usersService: UsersService, private router: Router) {
        this.isOpenAuthModal = this.usersService.isOpenAuthModal;
    }

    canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): boolean {
        if (this.isOpenAuthModal) {
            return true;
        }
        this.router.navigateByUrl("home");
        return false;
    }
}
```
(home.component.ts):
```
 onOpen(): void {
    this.usersService.isOpenAuthModal = true;
    ...
}
```
(auth-modal.component.ts):
```
 ngOnDestroy(): void {
    this.dialogRef.close();
    this.usersService.isOpenAuthModal = false;
    ...
  }
```

**Comment by AlinaShmain** [comment]
Новая проблема: если перейти по url /signIn, guard нас вернет на /home, а затем нажать на кнопку Login, то модальное окно откроется, в адресной строке останется также /home, а в <router-outlet> компонента модального окна вставится контент home компонента:
[example](https://drive.google.com/file/d/1bw7WDXOlo6Vyaaf6UHyfJVZZBHXrGapD/view?usp=sharing)

**Comment by AlinaShmain** [comment]
Решила проблему выше, оказалось в AuthModalGuard при проверке isOpenAuthModal из usersService, он был false, хотя перед открытием модального окна я меняла значение этой переменной на true, поэтому он открывал окно, а по маршруту /signIn пройти не давал, перенаправлял в /home и отображал в модальном окне содержимое компонента HomeComponent.
Было (auth-modal-guard.ts): 
```
isOpenAuthModal: boolean = false;
constructor(private usersService: UsersService, private router: Router, private route: ActivatedRoute) { 
       this.isOpenAuthModal = usersService.isOpenAuthModal;
}
canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): boolean {
        if (this.isOpenAuthModal) { // false 
            return true;
        }
        this.router.navigateByUrl(this.returnUrl);
        return false;
    }
```
Стало:
```
constructor(private usersService: UsersService, private router: Router, private route: ActivatedRoute) {
        this.route.queryParams.subscribe((params) => {
            this.returnUrl = params.returnUrl;
        });
}

canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): boolean {
        if (this.usersService.isOpenAuthModal) { // true
            return true;
        }
        this.router.navigateByUrl(this.returnUrl);
        return false;
}
```

Также изменила возврат к предыдущей странице в некоторых местах.

**Comment by AlinaShmain** [comment]
Не нашла в material custom theme с less, поэтому насчет стилизации material элементов вопрос открыт.

**Comment by cyclist-nn** [comment]
Для подключения стилей достаточно забрать css
https://material.angular.io/guide/theming#using-a-pre-built-theme
не надо вообще забирать scss файл

**Comment by AlinaShmain** [comment]
Убрала кастомную тему, добавила pre built, только в material все равно полно scss файлов
